export const t = {
  ar: {
    dir: "rtl",
    appName: "CliniMind",
    loginSubtitle: "مرحباً بعودتك، يرجى تسجيل الدخول للمتابعة",
    usernamePlaceholder: "اسم المستخدم أو البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    loginBtn: "تسجيل الدخول",
    loginError: "اسم المستخدم أو كلمة المرور غير صحيحة",
    logout: "تسجيل الخروج",
    clinicDirector: "مدير العيادة",
    // Tabs
    tabDashboard: "نظرة عامة",
    tabPatients: "إدارة المرضى",
    tabSchedule: "المواعيد",
    tabMedical: "الحالة الطبية والمخزون",
    tabBilling: "الفواتير والمدفوعات",
    tabExpenses: "المصاريف",
    tabReports: "التقارير",
    tabSettings: "الإعدادات",
    // Dashboard
    statsTotalPatients: "إجمالي المرضى",
    statsTodayVisitors: "مراجعو اليوم",
    statsPendingLabs: "نتائج المختبر المعلقة",
    statsTodayRevenue: "الإيرادات (اليوم)",
    statsMonthlyTrend: "هذا الشهر",
    statsInWaiting: "في الانتظار",
    statsCritical: "حرجة",
    urgentNotifications: "الإشعارات العاجلة",
    revenueTrends: "اتجاهات الإيرادات",
    last7Days: "آخر 7 أيام",
    newAlerts: "جديد",
    today: "اليوم",
    currency: "ريال",
    // Patients
    searchPlaceholder: "البحث بالاسم، رقم الملف، أو الهاتف...",
    addPatient: "إضافة مريض",
    addPatientTitle: "إضافة مريض جديد",
    savePatient: "حفظ المريض",
    fullNameLabel: "الاسم الكامل",
    phoneLabel: "رقم الهاتف",
    ageCategoryLabel: "الفئة العمرية",
    genderLabel: "الجنس",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    noPatientsFound: "لا يوجد مرضى يطابقون بحثك",
    lastVisitLabel: "آخر زيارة",
    // Schedule
    room: "غرفة",
    statusWaiting: "في الانتظار",
    statusExam: "جاري الفحص",
    statusArrived: "وصل",
    statusConfirmed: "مؤكد",
    statusCompleted: "تم الفحص",
    statusCancelled: "ملغي",
    statusNoShow: "غائب",
    addAppointment: "إضافة موعد",
    addAppointmentTitle: "إضافة موعد جديد",
    saveAppointment: "حفظ الموعد",
    selectDoctor: "اختيار الطبيب",
    selectPatient: "اختيار المريض",
    appointmentDate: "التاريخ",
    appointmentTime: "الوقت",
    appointmentReason: "السبب",
    appointmentType: "النوع",
    typeNormal: "عادي",
    typeFollowup: "متابعة",
    typeEmergency: "طوارئ",
    typeCheckup: "فحص دوري",
    noAppointments: "لا توجد مواعيد مجدولة لهذا اليوم",
    changeStatus: "تغيير الحالة",
    // Medical/Lab
    pharmacyStock: "مخزون الصيدلية",
    hospitalRequests: "طلبات المشفى",
    urgentCases: "حالات عاجلة",
    routineRequests: "طلبات روتينية",
    autoUpdate: "تحديث تلقائي",
    testType: "نوع التحليل",
    enterResults: "إدخال النتائج",
    details: "التفاصيل",
    startTest: "بدء التحليل",
    testCompleted: "تم إدخال النتائج وإرسال الإشعار",
    stockStatus: "تحديث المخزون الفوري",
    emergencyStock: "مخزون الطوارئ",
    lowStock: "منخفض",
  },
  en: {
    dir: "ltr",
    appName: "CliniMind",
    loginSubtitle: "Welcome back, please log in to continue",
    usernamePlaceholder: "Username or Email",
    passwordPlaceholder: "Password",
    forgotPassword: "Forgot Password?",
    loginBtn: "Log In",
    loginError: "Invalid username or password",
    logout: "Log Out",
    clinicDirector: "Clinic Director",
    // Tabs
    tabDashboard: "Dashboard",
    tabPatients: "Patients",
    tabSchedule: "Schedule",
    tabMedical: "Medical & Stock",
    tabBilling: "Billing & Payments",
    tabExpenses: "Expenses",
    tabReports: "Reports",
    tabSettings: "Settings",
    // Dashboard
    statsTotalPatients: "Total Patients",
    statsTodayVisitors: "Today's Visitors",
    statsPendingLabs: "Pending Lab Results",
    statsTodayRevenue: "Today's Revenue",
    statsMonthlyTrend: "this month",
    statsInWaiting: "in waiting",
    statsCritical: "critical",
    urgentNotifications: "Urgent Notifications",
    revenueTrends: "Revenue Trends",
    last7Days: "Last 7 Days",
    newAlerts: "new",
    today: "Today",
    currency: "SAR",
    // Patients
    searchPlaceholder: "Search by name, file number, or phone...",
    addPatient: "Add Patient",
    addPatientTitle: "Add New Patient",
    savePatient: "Save Patient",
    fullNameLabel: "Full Name",
    phoneLabel: "Phone Number",
    ageCategoryLabel: "Age Category",
    genderLabel: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    noPatientsFound: "No patients match your search",
    lastVisitLabel: "Last Visit",
    // Schedule
    room: "Room",
    statusWaiting: "Waiting",
    statusExam: "In Exam",
    statusArrived: "Arrived",
    statusConfirmed: "Confirmed",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusNoShow: "No Show",
    addAppointment: "Add Appointment",
    addAppointmentTitle: "Add New Appointment",
    saveAppointment: "Save Appointment",
    selectDoctor: "Select Doctor",
    selectPatient: "Select Patient",
    appointmentDate: "Date",
    appointmentTime: "Time",
    appointmentReason: "Reason",
    appointmentType: "Type",
    typeNormal: "Normal",
    typeFollowup: "Follow-up",
    typeEmergency: "Emergency",
    typeCheckup: "Check-up",
    noAppointments: "No appointments scheduled for this day",
    changeStatus: "Change status",
    // Medical/Lab
    pharmacyStock: "Pharmacy Stock",
    hospitalRequests: "Hospital Requests",
    urgentCases: "Urgent Cases",
    routineRequests: "Routine Requests",
    autoUpdate: "Auto Update",
    testType: "Test Type",
    enterResults: "Enter Results",
    details: "Details",
    startTest: "Start Test",
    testCompleted: "Results entered and doctor notified",
    stockStatus: "Real-time Stock Status",
    emergencyStock: "Emergency Stock",
    lowStock: "Low Stock",
  },
  fr: {
    dir: "ltr",
    appName: "CliniMind",
    loginSubtitle: "Ravi de vous revoir, veuillez vous connecter pour continuer",
    usernamePlaceholder: "Nom d'utilisateur ou Email",
    passwordPlaceholder: "Mot de passe",
    forgotPassword: "Mot de passe oublié?",
    loginBtn: "Se Connecter",
    loginError: "Nom d'utilisateur ou mot de passe incorrect",
    logout: "Déconnexion",
    clinicDirector: "Directeur de Clinique",
    // Tabs
    tabDashboard: "Aperçu",
    tabPatients: "Patients",
    tabSchedule: "Rendez-vous",
    tabMedical: "Médical & Stock",
    tabBilling: "Facturation & Encaissement",
    tabExpenses: "Dépenses",
    tabReports: "Rapports",
    tabSettings: "Paramètres",
    // Dashboard
    statsTotalPatients: "Total Patients",
    statsTodayVisitors: "Visiteurs du Jour",
    statsPendingLabs: "Analyses en Attente",
    statsTodayRevenue: "Revenus (Jour)",
    statsMonthlyTrend: "ce mois",
    statsInWaiting: "en attente",
    statsCritical: "critiques",
    urgentNotifications: "Notifications Urgentes",
    revenueTrends: "Tendances des Revenus",
    last7Days: "7 Derniers Jours",
    newAlerts: "nouveau",
    today: "Aujourd'hui",
    currency: "SAR",
    // Patients
    searchPlaceholder: "Rechercher par nom, dossier ou tél...",
    addPatient: "Ajouter Patient",
    addPatientTitle: "Ajouter un Nouveau Patient",
    savePatient: "Enregistrer",
    fullNameLabel: "Nom Complet",
    phoneLabel: "Numéro de Téléphone",
    ageCategoryLabel: "Catégorie d'Âge",
    genderLabel: "Genre",
    genderMale: "Homme",
    genderFemale: "Femme",
    noPatientsFound: "Aucun patient ne correspond",
    lastVisitLabel: "Dernière Visite",
    // Schedule
    room: "Salle",
    statusWaiting: "En Attente",
    statusExam: "En Examen",
    statusArrived: "Arrivé",
    statusConfirmed: "Confirmé",
    statusCompleted: "Terminé",
    statusCancelled: "Annulé",
    statusNoShow: "Absent",
    addAppointment: "Ajouter Rendez-vous",
    addAppointmentTitle: "Ajouter un Rendez-vous",
    saveAppointment: "Enregistrer",
    selectDoctor: "Sélectionner le médecin",
    selectPatient: "Sélectionner le patient",
    appointmentDate: "Date",
    appointmentTime: "Heure",
    appointmentReason: "Motif",
    appointmentType: "Type",
    typeNormal: "Normal",
    typeFollowup: "Suivi",
    typeEmergency: "Urgence",
    typeCheckup: "Bilan",
    noAppointments: "Aucun rendez-vous programmé pour aujourd'hui",
    changeStatus: "Changer le statut",
    // Medical/Lab
    pharmacyStock: "Stock Pharmacie",
    hospitalRequests: "Demandes Hôpital",
    urgentCases: "Cas Urgents",
    routineRequests: "Demandes Routinières",
    autoUpdate: "Mise à jour auto",
    testType: "Type d'Analyse",
    enterResults: "Saisir Résultats",
    details: "Détails",
    startTest: "Lancer l'Analyse",
    testCompleted: "Résultats saisis et médecin notifié",
    stockStatus: "État de Stock Instantané",
    emergencyStock: "Stock d'Urgence",
    lowStock: "Faible",
  },
};

export type LangKey = "ar" | "en" | "fr";
