export const t = {
  ar: {
    dir: "rtl",
    appName: "CliniMind",
    loginSubtitle: "مرحباً بعودتك، يرجى تسجيل الدخول للمتابعة",
    usernamePlaceholder: "اسم المستخدم أو البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    loginBtn: "تسجيل الدخول",
    biometricLogin: "تسجيل الدخول البيومتري",
    biometricToast: "جاري تهيئة القارئ البيومتري...",
    loginError: "اسم المستخدم أو كلمة المرور غير صحيحة",
    logout: "تسجيل الخروج",
    clinicDirector: "مدير العيادة",
    // Tabs
    tabDashboard: "نظرة عامة",
    tabPatients: "إدارة المرضى",
    tabSchedule: "المواعيد",
    tabMedical: "الحالة الطبية والمخزون",
    tabBilling: "الفواتير والمدفوعات",
    tabExpenses: "المصاريف",
    tabReports: "التقارير",
    tabSettings: "الإعدادات",
    // Dashboard
    statsTotalPatients: "إجمالي المرضى",
    statsTodayVisitors: "مراجعو اليوم",
    statsPendingLabs: "نتائج المختبر المعلقة",
    statsTodayRevenue: "الإيرادات (اليوم)",
    statsMonthlyTrend: "هذا الشهر",
    statsInWaiting: "في الانتظار",
    statsCritical: "حرجة",
    urgentNotifications: "الإشعارات العاجلة",
    revenueTrends: "اتجاهات الإيرادات",
    last7Days: "آخر 7 أيام",
    newAlerts: "جديد",
    potassiumAlert: "المريض: أحمد محمد - مستوى البوتاسيوم مرتفع جداً (6.5 mmol/L)",
    stockAlert: "مخزون القفازات المعقمة (حجم L) أقل من الحد الأدنى",
    tenMinsAgo: "منذ 10 دقائق",
    oneHourAgo: "منذ ساعة",
    today: "اليوم",
    currency: "ريال",
    // Patients
    searchPlaceholder: "البحث بالاسم، رقم الملف، أو الهاتف...",
    addPatient: "إضافة مريض",
    addPatientTitle: "إضافة مريض جديد",
    savePatient: "حفظ المريض",
    fullNameLabel: "الاسم الكامل",
    phoneLabel: "رقم الهاتف",
    ageCategoryLabel: "الفئة العمرية",
    genderLabel: "الجنس",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    noPatientsFound: "لا يوجد مرضى يطابقون بحثك",
    lastVisitLabel: "آخر زيارة",
    // Schedule
    october2023: "أكتوبر 2023",
    familyMedicine: "طب الأسرة",
    cardiology: "أمراض القلب",
    room: "غرفة",
    statusWaiting: "في الانتظار",
    statusExam: "جاري الفحص",
    statusArrived: "وصل",
    statusConfirmed: "مؤكد",
    // Medical/Lab
    pharmacyStock: "مخزون الصيدلية",
    hospitalRequests: "طلبات المشفى",
    urgentCases: "حالات عاجلة",
    routineRequests: "طلبات روتينية",
    autoUpdate: "تحديث تلقائي",
    testType: "نوع التحليل",
    enterResults: "إدخال النتائج",
    details: "التفاصيل",
    startTest: "بدء التحليل",
    testCompleted: "تم إدخال النتائج وإرسال الإشعار",
    stockStatus: "تحديث المخزون الفوري",
    emergencyStock: "مخزون الطوارئ",
    lowStock: "منخفض",
  },
  en: {
    dir: "ltr",
    appName: "CliniMind",
    loginSubtitle: "Welcome back, please log in to continue",
    usernamePlaceholder: "Username or Email",
    passwordPlaceholder: "Password",
    forgotPassword: "Forgot Password?",
    loginBtn: "Log In",
    biometricLogin: "Biometric Login",
    biometricToast: "Initializing biometric reader...",
    loginError: "Invalid username or password",
    logout: "Log Out",
    clinicDirector: "Clinic Director",
    // Tabs
    tabDashboard: "Dashboard",
    tabPatients: "Patients",
    tabSchedule: "Schedule",
    tabMedical: "Medical & Stock",
    tabBilling: "Billing & Payments",
    tabExpenses: "Expenses",
    tabReports: "Reports",
    tabSettings: "Settings",
    // Dashboard
    statsTotalPatients: "Total Patients",
    statsTodayVisitors: "Today's Visitors",
    statsPendingLabs: "Pending Lab Results",
    statsTodayRevenue: "Today's Revenue",
    statsMonthlyTrend: "this month",
    statsInWaiting: "in waiting",
    statsCritical: "critical",
    urgentNotifications: "Urgent Notifications",
    revenueTrends: "Revenue Trends",
    last7Days: "Last 7 Days",
    newAlerts: "new",
    potassiumAlert: "Patient: Ahmad Mohamed - Potassium level very high (6.5 mmol/L)",
    stockAlert: "Sterile gloves stock (Size L) below safety threshold",
    tenMinsAgo: "10 mins ago",
    oneHourAgo: "1 hour ago",
    today: "Today",
    currency: "SAR",
    // Patients
    searchPlaceholder: "Search by name, file number, or phone...",
    addPatient: "Add Patient",
    addPatientTitle: "Add New Patient",
    savePatient: "Save Patient",
    fullNameLabel: "Full Name",
    phoneLabel: "Phone Number",
    ageCategoryLabel: "Age Category",
    genderLabel: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    noPatientsFound: "No patients match your search",
    lastVisitLabel: "Last Visit",
    // Schedule
    october2023: "October 2023",
    familyMedicine: "Family Medicine",
    cardiology: "Cardiology",
    room: "Room",
    statusWaiting: "Waiting",
    statusExam: "In Exam",
    statusArrived: "Arrived",
    statusConfirmed: "Confirmed",
    // Medical/Lab
    pharmacyStock: "Pharmacy Stock",
    hospitalRequests: "Hospital Requests",
    urgentCases: "Urgent Cases",
    routineRequests: "Routine Requests",
    autoUpdate: "Auto Update",
    testType: "Test Type",
    enterResults: "Enter Results",
    details: "Details",
    startTest: "Start Test",
    testCompleted: "Results entered and doctor notified",
    stockStatus: "Real-time Stock Status",
    emergencyStock: "Emergency Stock",
    lowStock: "Low Stock",
  },
  fr: {
    dir: "ltr",
    appName: "CliniMind",
    loginSubtitle: "Ravi de vous revoir, veuillez vous connecter pour continuer",
    usernamePlaceholder: "Nom d'utilisateur ou Email",
    passwordPlaceholder: "Mot de passe",
    forgotPassword: "Mot de passe oublié?",
    loginBtn: "Se Connecter",
    biometricLogin: "Connexion Biométrique",
    biometricToast: "Initialisation du lecteur biométrique...",
    loginError: "Nom d'utilisateur ou mot de passe incorrect",
    logout: "Déconnexion",
    clinicDirector: "Directeur de Clinique",
    // Tabs
    tabDashboard: "Aperçu",
    tabPatients: "Patients",
    tabSchedule: "Rendez-vous",
    tabMedical: "Médical & Stock",
    tabBilling: "Facturation & Encaissement",
    tabExpenses: "Dépenses",
    tabReports: "Rapports",
    tabSettings: "Paramètres",
    // Dashboard
    statsTotalPatients: "Total Patients",
    statsTodayVisitors: "Visiteurs du Jour",
    statsPendingLabs: "Analyses en Attente",
    statsTodayRevenue: "Revenus (Jour)",
    statsMonthlyTrend: "ce mois",
    statsInWaiting: "en attente",
    statsCritical: "critiques",
    urgentNotifications: "Notifications Urgentes",
    revenueTrends: "Tendances des Revenus",
    last7Days: "7 Derniers Jours",
    newAlerts: "nouveau",
    potassiumAlert: "Patient: Ahmad Mohamed - Niveau de potassium très élevé (6.5 mmol/L)",
    stockAlert: "Stock de gants stériles (Taille L) inférieur au seuil",
    tenMinsAgo: "il y a 10 min",
    oneHourAgo: "il y a 1 h",
    today: "Aujourd'hui",
    currency: "SAR",
    // Patients
    searchPlaceholder: "Rechercher par nom, dossier ou tél...",
    addPatient: "Ajouter Patient",
    addPatientTitle: "Ajouter un Nouveau Patient",
    savePatient: "Enregistrer",
    fullNameLabel: "Nom Complet",
    phoneLabel: "Numéro de Téléphone",
    ageCategoryLabel: "Catégorie d'Âge",
    genderLabel: "Genre",
    genderMale: "Homme",
    genderFemale: "Femme",
    noPatientsFound: "Aucun patient ne correspond",
    lastVisitLabel: "Dernière Visite",
    // Schedule
    october2023: "Octobre 2023",
    familyMedicine: "Médecine Familiale",
    cardiology: "Cardiologie",
    room: "Salle",
    statusWaiting: "En Attente",
    statusExam: "En Examen",
    statusArrived: "Arrivé",
    statusConfirmed: "Confirmé",
    // Medical/Lab
    pharmacyStock: "Stock Pharmacie",
    hospitalRequests: "Demandes Hôpital",
    urgentCases: "Cas Urgents",
    routineRequests: "Demandes Routinières",
    autoUpdate: "Mise à jour auto",
    testType: "Type d'Analyse",
    enterResults: "Saisir Résultats",
    details: "Détails",
    startTest: "Lancer l'Analyse",
    testCompleted: "Résultats saisis et médecin notifié",
    stockStatus: "État de Stock Instantané",
    emergencyStock: "Stock d'Urgence",
    lowStock: "Faible",
  },
};

export type LangKey = "ar" | "en" | "fr";
